theme: jekyll-theme-dinky
title: SAE TeMV2 2023-2024
description: This pages contains material, exercises and links in support of SAE TeMV2 Course
logo: https://upload.wikimedia.org/wikipedia/commons/9/9e/FallPando02.jpg
show_downloads: false