plugins:
- jekyll-remote-theme
remote_theme: BDHU/minimalist
title: "SAE TeMV2 2023-2024"
description: "Pagina di supporto al corso Tecniche e Metodologie dei Videogiochi 2"
avatar: https://andguasta.github.io/sae-temv2/assets/img/CourseImage.png
